# -*- coding: utf-8 -*-
"""fraud transaction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tdgUAurKmBcIiaQYVTg_fU3S8wOkaY0i
"""

# ============================================================
# FRAUD DETECTION MODEL - Google Colab Ready
# By Abhishek | Optimized & Clean Version
# ============================================================

# ── 1. INSTALL & IMPORTS ────────────────────────────────────
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (classification_report, confusion_matrix,
                             ConfusionMatrixDisplay, roc_curve, auc)
from statsmodels.stats.outliers_influence import variance_inflation_factor

import pandas as pd

# --- 2 .load data ---
!pip install kaggle -q
# from google.colab import files
# files.upload()  # upload kaggle.json
# !mkdir -p ~/.kaggle && cp kaggle.json ~/.kaggle/ && chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d ealaxi/paysim1 --unzip
df = pd.read_csv('PS_20174392719_1491204439457_log.csv')

# df = pd.read_csv('fraud.csv')  # <-- change filename if needed
print("Shape:", df.shape)
print(df.head())

# ── 3. BASIC EDA ─────────────────────────────────────────────
print("\nNull values:", df.isnull().values.any())
print(df.info())

fraud   = len(df[df.isFraud == 1])
legit   = len(df[df.isFraud == 0])
print(f"\nLegit: {legit} ({legit/(fraud+legit)*100:.4f}%)")
print(f"Fraud: {fraud} ({fraud/(fraud+legit)*100:.4f}%)")

# ── 4. VISUALISATION ─────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Class imbalance bar
df['isFraud'].value_counts().plot(kind='bar', ax=axes[0],
    color=['purple', 'salmon'], rot=0)
axes[0].set_xticklabels(['Legit', 'Fraud'])
axes[0].set_title('Transaction Class Distribution')
axes[0].set_ylabel('Count')

# Correlation heatmap
corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True, fmt='.2f', cmap='plasma', ax=axes[1])
axes[1].set_title('Correlation Heatmap')
plt.tight_layout()
plt.show()

# ── 5. PREPROCESSING ─────────────────────────────────────────
new_df = df.copy()

# Label encode categorical columns
le = LabelEncoder()
for col in new_df.select_dtypes(include='object').columns:
    new_df[col] = le.fit_transform(new_df[col].astype(str))

# ── 6. MULTICOLLINEARITY (VIF) ───────────────────────────────
def calc_vif(data):
    vif = pd.DataFrame()
    vif['Variable'] = data.columns
    vif['VIF'] = [variance_inflation_factor(data.values, i)
                  for i in range(data.shape[1])]
    return vif

print("\nVIF Before feature engineering:")
print(calc_vif(new_df))

# Fix multicollinearity: combine correlated pairs
new_df['Actual_amount_orig'] = new_df['oldbalanceOrg']  - new_df['newbalanceOrig']
new_df['Actual_amount_dest'] = new_df['oldbalanceDest'] - new_df['newbalanceDest']
new_df['TransactionPath']    = new_df['nameOrig']       + new_df['nameDest']

drop_cols = ['oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest',
             'newbalanceDest', 'step', 'nameOrig', 'nameDest']
new_df.drop(columns=drop_cols, inplace=True)

print("\nVIF After feature engineering:")
print(calc_vif(new_df))

# ── 7. SCALING & SPLIT ───────────────────────────────────────
scaler = StandardScaler()
new_df['NormalizedAmount'] = scaler.fit_transform(
    new_df[['amount']].values)
new_df.drop(columns=['amount'], inplace=True)

X = new_df.drop(columns=['isFraud'])
Y = new_df['isFraud']

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.3, random_state=42)

print(f"\nTrain: {X_train.shape} | Test: {X_test.shape}")

# ── 8. MODEL TRAINING ────────────────────────────────────────
# Decision Tree
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, Y_train)
Y_pred_dt = dt.predict(X_test)

# Random Forest (faster with n_jobs=-1)
rf = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
rf.fit(X_train, Y_train)
Y_pred_rf = rf.predict(X_test)

# ── 9. EVALUATION ────────────────────────────────────────────
for name, Y_pred in [('Decision Tree', Y_pred_dt), ('Random Forest', Y_pred_rf)]:
    print(f"\n{'='*50}")
    print(f"  {name}")
    print(f"{'='*50}")
    tn, fp, fn, tp = confusion_matrix(Y_test, Y_pred).ravel()
    print(f"TP={tp}  FP={fp}  TN={tn}  FN={fn}")
    print(classification_report(Y_test, Y_pred))

# ── 10. CONFUSION MATRIX PLOTS ───────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
for ax, name, Y_pred, cmap in zip(
        axes,
        ['Decision Tree', 'Random Forest'],
        [Y_pred_dt, Y_pred_rf],
        ['inferno', 'viridis']):
    cm = confusion_matrix(Y_test, Y_pred)
    ConfusionMatrixDisplay(cm).plot(ax=ax, cmap=cmap)
    ax.set_title(f'Confusion Matrix – {name}')
plt.tight_layout()
plt.show()

# ── 11. ROC CURVES ───────────────────────────────────────────
plt.figure(figsize=(8, 6))
for name, model in [('Decision Tree', dt), ('Random Forest', rf)]:
    fpr, tpr, _ = roc_curve(Y_test, model.predict_proba(X_test)[:, 1])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'{name} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'r--', label='Random')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison')
plt.legend(loc='lower right')
plt.tight_layout()
plt.show()

# ── 12. FEATURE IMPORTANCE (Random Forest) ───────────────────
feat_imp = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=False)
plt.figure(figsize=(10, 5))
feat_imp.plot(kind='bar', color='steelblue')
plt.title('Feature Importance – Random Forest')
plt.ylabel('Importance')
plt.tight_layout()
plt.show()
print("\nTop Features:\n", feat_imp)

